"""add_variations_and_size_stocks

Revision ID: 9965ca7f294b
Revises: g3h4i5j6k7l8
Create Date: 2025-12-06 10:14:15.894304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9965ca7f294b'
down_revision: Union[str, None] = 'g3h4i5j6k7l8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('variations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('color_hex', sa.String(length=7), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('sale_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('images', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_variations_product_id'), 'variations', ['product_id'], unique=False)
    op.create_table('size_stocks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('variation_id', sa.UUID(), nullable=False),
    sa.Column('size', sa.Enum('XXS', 'XS', 'S', 'M', 'L', 'XL', 'XXL', 'XXXL', name='sizeenum'), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['variation_id'], ['variations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('variation_id', 'size', name='uq_variation_size')
    )
    op.create_index(op.f('ix_size_stocks_variation_id'), 'size_stocks', ['variation_id'], unique=False)
    op.alter_column('cart_items', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('manage_preferences', 'favorite_designers',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=False)
    op.alter_column('manage_preferences', 'favorite_categories',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=False)
    op.alter_column('vendor_applications', 'status',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint('vendor_applications_email_key', 'vendor_applications', type_='unique')
    op.drop_index('ix_vendor_applications_email', table_name='vendor_applications')
    op.create_index(op.f('ix_vendor_applications_email'), 'vendor_applications', ['email'], unique=True)
    op.alter_column('vendor_assets', 'display_order',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('vendor_assets', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('vendor_notifications', 'is_read',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('vendor_notifications', 'email_sent',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('vendor_otps', 'attempts',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('vendor_otps', 'max_attempts',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('vendor_otps', 'is_used',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('vendor_payment_methods', 'is_default',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('vendor_pickups', 'order_type',
               existing_type=postgresql.ENUM('RTW', 'MADE_TO_ORDER', 'CUSTOM', name='ordertype'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('vendor_pickups', 'status',
               existing_type=postgresql.ENUM('SCHEDULED', 'IN_TRANSIT', 'DELIVERED_TO_QC', 'QC_APPROVED', 'QC_REJECTED', 'SHIPPED_TO_CUSTOMER', 'COMPLETED', 'CANCELLED', name='pickupstatus'),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint('vendor_pickups_qc_approved_by_fkey', 'vendor_pickups', type_='foreignkey')
    op.create_foreign_key(None, 'vendor_pickups', 'users', ['qc_approved_by'], ['id'])
    op.alter_column('vendors', 'store_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('vendors', 'is_onboarding',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('vendors', 'brand_info_completed',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('vendors', 'payout_info_completed',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_index('ix_wishlists_product_id', table_name='wishlists')
    op.drop_index('ix_wishlists_user_id', table_name='wishlists')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_wishlists_user_id', 'wishlists', ['user_id'], unique=False)
    op.create_index('ix_wishlists_product_id', 'wishlists', ['product_id'], unique=False)
    op.alter_column('vendors', 'payout_info_completed',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('vendors', 'brand_info_completed',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('vendors', 'is_onboarding',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('vendors', 'store_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.drop_constraint(None, 'vendor_pickups', type_='foreignkey')
    op.create_foreign_key('vendor_pickups_qc_approved_by_fkey', 'vendor_pickups', 'users', ['qc_approved_by'], ['id'], ondelete='SET NULL')
    op.alter_column('vendor_pickups', 'status',
               existing_type=postgresql.ENUM('SCHEDULED', 'IN_TRANSIT', 'DELIVERED_TO_QC', 'QC_APPROVED', 'QC_REJECTED', 'SHIPPED_TO_CUSTOMER', 'COMPLETED', 'CANCELLED', name='pickupstatus'),
               server_default=sa.text("'SCHEDULED'::pickupstatus"),
               existing_nullable=False)
    op.alter_column('vendor_pickups', 'order_type',
               existing_type=postgresql.ENUM('RTW', 'MADE_TO_ORDER', 'CUSTOM', name='ordertype'),
               server_default=sa.text("'RTW'::ordertype"),
               existing_nullable=False)
    op.alter_column('vendor_payment_methods', 'is_default',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('vendor_otps', 'is_used',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('vendor_otps', 'max_attempts',
               existing_type=sa.INTEGER(),
               server_default=sa.text('5'),
               existing_nullable=False)
    op.alter_column('vendor_otps', 'attempts',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('vendor_notifications', 'email_sent',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('vendor_notifications', 'is_read',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('vendor_assets', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('vendor_assets', 'display_order',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.drop_index(op.f('ix_vendor_applications_email'), table_name='vendor_applications')
    op.create_index('ix_vendor_applications_email', 'vendor_applications', ['email'], unique=False)
    op.create_unique_constraint('vendor_applications_email_key', 'vendor_applications', ['email'])
    op.alter_column('vendor_applications', 'status',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'pending_review'::character varying"),
               existing_nullable=False)
    op.alter_column('manage_preferences', 'favorite_categories',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'[]'::jsonb"),
               existing_nullable=False)
    op.alter_column('manage_preferences', 'favorite_designers',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'[]'::jsonb"),
               existing_nullable=False)
    op.alter_column('cart_items', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.drop_index(op.f('ix_size_stocks_variation_id'), table_name='size_stocks')
    op.drop_table('size_stocks')
    op.drop_index(op.f('ix_variations_product_id'), table_name='variations')
    op.drop_table('variations')
    # ### end Alembic commands ###
