"""Milestone 2 compatibility writer and positive classification tooling.

Revision ID: a1b2c3d4e5f6
Revises: a0b1c2d3e4f5
"""

from alembic import op

revision = "a1b2c3d4e5f6"
down_revision = "a0b1c2d3e4f5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        r"""
CREATE TABLE order_workflow_classifications(order_id uuid PRIMARY KEY, cohort varchar(40) NOT NULL, policy_version varchar(40) NOT NULL, access_mode varchar(20) NOT NULL, evidence_kind varchar(60) NOT NULL, evidence_reference varchar(200) NOT NULL, migration_run_id uuid NOT NULL REFERENCES order_workflow_migration_runs(id) ON DELETE RESTRICT, classified_at timestamptz NOT NULL DEFAULT statement_timestamp(), classified_by varchar(100) NOT NULL, notes_hash char(64) NOT NULL, CONSTRAINT ck_order_workflow_classifications_values CHECK(cohort IN ('legacy_pre_bridge','legacy_ambiguous_quarantined','domestic_checkout_v1') AND access_mode IN ('authenticated','guest_capability','legacy_quarantined')), CONSTRAINT ck_order_workflow_classifications_evidence CHECK(evidence_kind ~ '^[A-Za-z0-9][A-Za-z0-9._:-]{0,59}$' AND evidence_reference ~ '^[!-~]{1,200}$' AND classified_by ~ '^[A-Za-z0-9][A-Za-z0-9._:-]{0,99}$' AND notes_hash ~ '^[0-9a-f]{64}$'));
CREATE OR REPLACE FUNCTION protect_order_workflow_truth() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF TG_OP='DELETE' THEN RETURN OLD; END IF; IF OLD.workflow_cohort IS NULL AND OLD.workflow_policy_version IS NULL AND OLD.checkout_access_mode IS NULL AND NEW.workflow_cohort IS NOT NULL AND NEW.workflow_policy_version IS NOT NULL AND NEW.checkout_access_mode IS NOT NULL THEN RETURN NEW; END IF; IF OLD.workflow_cohort IS DISTINCT FROM NEW.workflow_cohort OR OLD.workflow_policy_version IS DISTINCT FROM NEW.workflow_policy_version OR OLD.checkout_access_mode IS DISTINCT FROM NEW.checkout_access_mode OR (OLD.checkout_estimate_selection_id IS NOT NULL AND OLD.checkout_estimate_selection_id IS DISTINCT FROM NEW.checkout_estimate_selection_id) THEN RAISE EXCEPTION 'immutable order workflow truth'; END IF; RETURN NEW; END $$;
CREATE TRIGGER orders_workflow_immutable BEFORE UPDATE OR DELETE ON orders FOR EACH ROW EXECUTE FUNCTION protect_order_workflow_truth();
CREATE OR REPLACE FUNCTION protect_append_only_checkout_prerequisite() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'immutable checkout prerequisite evidence'; END $$;
CREATE TRIGGER order_workflow_classifications_append_only BEFORE UPDATE OR DELETE ON order_workflow_classifications FOR EACH ROW EXECUTE FUNCTION protect_append_only_checkout_prerequisite();
CREATE TRIGGER order_workflow_migration_runs_no_delete BEFORE DELETE ON order_workflow_migration_runs FOR EACH ROW EXECUTE FUNCTION protect_append_only_checkout_prerequisite();
CREATE OR REPLACE FUNCTION protect_order_item_inventory_snapshot() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF OLD.inventory_policy IS NULL AND OLD.inventory_subject_kind IS NULL AND OLD.inventory_subject_id IS NULL AND OLD.inventory_source_product_id IS NULL AND OLD.inventory_source_catalogue_version IS NULL AND OLD.inventory_source_evidence_hash IS NULL AND OLD.inventory_policy_snapshot_at IS NULL THEN RETURN NEW; END IF; IF OLD.inventory_policy IS DISTINCT FROM NEW.inventory_policy OR OLD.inventory_subject_kind IS DISTINCT FROM NEW.inventory_subject_kind OR OLD.inventory_subject_id IS DISTINCT FROM NEW.inventory_subject_id OR OLD.inventory_source_product_id IS DISTINCT FROM NEW.inventory_source_product_id OR OLD.inventory_source_catalogue_version IS DISTINCT FROM NEW.inventory_source_catalogue_version OR OLD.inventory_source_evidence_hash IS DISTINCT FROM NEW.inventory_source_evidence_hash OR OLD.inventory_policy_snapshot_at IS DISTINCT FROM NEW.inventory_policy_snapshot_at THEN RAISE EXCEPTION 'immutable order item inventory snapshot'; END IF; RETURN NEW; END $$;
CREATE TRIGGER order_items_inventory_snapshot_immutable BEFORE UPDATE ON order_items FOR EACH ROW EXECUTE FUNCTION protect_order_item_inventory_snapshot();
CREATE OR REPLACE FUNCTION protect_order_current_owner() RETURNS trigger LANGUAGE plpgsql AS $$ DECLARE order_customer uuid; BEGIN IF TG_OP='DELETE' THEN IF pg_trigger_depth()>1 THEN RETURN OLD; END IF; RAISE EXCEPTION 'order current owner projection cannot be deleted'; END IF; IF TG_OP='INSERT' THEN SELECT customer_id INTO order_customer FROM orders WHERE id=NEW.order_id; IF order_customer IS NULL OR NEW.original_customer_id IS DISTINCT FROM order_customer THEN RAISE EXCEPTION 'original owner must equal order customer'; END IF; RETURN NEW; END IF; IF OLD.order_id IS DISTINCT FROM NEW.order_id OR OLD.original_customer_id IS DISTINCT FROM NEW.original_customer_id THEN RAISE EXCEPTION 'immutable original owner identity'; END IF; IF OLD.current_authenticated_user_id IS NULL AND OLD.claim_capability_id IS NULL AND OLD.claim_idempotency_key IS NULL AND OLD.claimed_at IS NULL THEN RETURN NEW; END IF; IF OLD.current_authenticated_user_id IS DISTINCT FROM NEW.current_authenticated_user_id OR OLD.claim_capability_id IS DISTINCT FROM NEW.claim_capability_id OR OLD.claim_idempotency_key IS DISTINCT FROM NEW.claim_idempotency_key OR OLD.claimed_at IS DISTINCT FROM NEW.claimed_at THEN RAISE EXCEPTION 'owner claim transition is immutable after claim'; END IF; RETURN NEW; END $$;
CREATE TRIGGER order_current_owners_identity_immutable BEFORE INSERT OR UPDATE OR DELETE ON order_current_owners FOR EACH ROW EXECUTE FUNCTION protect_order_current_owner();
CREATE OR REPLACE FUNCTION classify_compatibility_order_before_insert() RETURNS trigger LANGUAGE plpgsql AS $$ DECLARE active_run uuid; DECLARE cutover_at timestamptz; BEGIN SELECT id,classification_cutover_at INTO active_run,cutover_at FROM order_workflow_migration_runs ORDER BY compatibility_writer_started_at DESC,id DESC LIMIT 1; IF active_run IS NULL THEN RETURN NEW; END IF; IF cutover_at IS NOT NULL AND NEW.workflow_cohort='domestic_checkout_v1' AND NEW.workflow_policy_version='domestic_checkout_v1' AND NEW.checkout_access_mode IN ('authenticated','guest_capability') THEN RETURN NEW; END IF; IF NEW.workflow_cohort IS NULL AND NEW.workflow_policy_version IS NULL AND NEW.checkout_access_mode IS NULL THEN NEW.workflow_cohort:='legacy_pre_bridge'; NEW.workflow_policy_version:='legacy_pre_bridge_v1'; NEW.checkout_access_mode:='authenticated'; ELSIF NEW.workflow_cohort IS NULL OR NEW.workflow_policy_version IS NULL OR NEW.checkout_access_mode IS NULL THEN RAISE EXCEPTION 'compatibility writer requires complete workflow truth'; ELSIF NEW.workflow_cohort<>'legacy_pre_bridge' OR NEW.workflow_policy_version<>'legacy_pre_bridge_v1' OR NEW.checkout_access_mode NOT IN ('authenticated','guest_capability') THEN RAISE EXCEPTION 'compatibility writer requires legacy workflow truth'; END IF; RETURN NEW; END $$;
CREATE TRIGGER orders_compatibility_writer_before_insert BEFORE INSERT ON orders FOR EACH ROW EXECUTE FUNCTION classify_compatibility_order_before_insert();
CREATE OR REPLACE FUNCTION record_compatibility_order_after_insert() RETURNS trigger LANGUAGE plpgsql AS $$ DECLARE active_run uuid; DECLARE release_reference text; DECLARE candidate_hash text; BEGIN SELECT id,compatibility_writer_release_id||':'||deployment_identity INTO active_run,release_reference FROM order_workflow_migration_runs ORDER BY compatibility_writer_started_at DESC,id DESC LIMIT 1; IF active_run IS NULL THEN RETURN NEW; END IF; INSERT INTO order_current_owners(order_id,original_customer_id) VALUES(NEW.id,NEW.customer_id); candidate_hash:=encode(sha256(convert_to(NEW.id::text||'|'||NEW.workflow_cohort||'|'||NEW.workflow_policy_version||'|'||NEW.checkout_access_mode||'|positive_release_or_bridge_evidence|'||release_reference,'UTF8')),'hex'); INSERT INTO order_workflow_classifications(order_id,cohort,policy_version,access_mode,evidence_kind,evidence_reference,migration_run_id,classified_by,notes_hash) VALUES(NEW.id,NEW.workflow_cohort,NEW.workflow_policy_version,NEW.checkout_access_mode,'positive_release_or_bridge_evidence',release_reference,active_run,'compatibility_writer',candidate_hash); RETURN NEW; END $$;
CREATE TRIGGER orders_compatibility_writer_after_insert AFTER INSERT ON orders FOR EACH ROW EXECUTE FUNCTION record_compatibility_order_after_insert();
CREATE TRIGGER checkout_shipping_estimates_immutable BEFORE UPDATE OR DELETE ON checkout_shipping_estimates FOR EACH ROW EXECUTE FUNCTION protect_append_only_checkout_prerequisite(); CREATE TRIGGER checkout_shipping_estimate_options_immutable BEFORE UPDATE OR DELETE ON checkout_shipping_estimate_options FOR EACH ROW EXECUTE FUNCTION protect_append_only_checkout_prerequisite(); CREATE TRIGGER checkout_shipping_estimate_selections_immutable BEFORE UPDATE OR DELETE ON checkout_shipping_estimate_selections FOR EACH ROW EXECUTE FUNCTION protect_append_only_checkout_prerequisite(); CREATE TRIGGER order_guest_capabilities_no_delete BEFORE DELETE ON order_guest_capabilities FOR EACH ROW EXECUTE FUNCTION protect_append_only_checkout_prerequisite(); CREATE TRIGGER order_inventory_coverage_immutable BEFORE UPDATE OR DELETE ON order_inventory_coverage FOR EACH ROW EXECUTE FUNCTION protect_append_only_checkout_prerequisite();
"""
    )


def downgrade() -> None:
    op.execute(
        "DO $$ BEGIN IF EXISTS(SELECT 1 FROM order_workflow_classifications) OR EXISTS(SELECT 1 FROM order_workflow_migration_runs) THEN RAISE EXCEPTION 'refusing destructive Milestone 2 downgrade: classification audit data exists'; END IF; END $$"
    )
    op.execute(
        "DROP TRIGGER order_inventory_coverage_immutable ON order_inventory_coverage; DROP TRIGGER order_guest_capabilities_no_delete ON order_guest_capabilities; DROP TRIGGER checkout_shipping_estimate_selections_immutable ON checkout_shipping_estimate_selections; DROP TRIGGER checkout_shipping_estimate_options_immutable ON checkout_shipping_estimate_options; DROP TRIGGER checkout_shipping_estimates_immutable ON checkout_shipping_estimates; DROP TRIGGER orders_compatibility_writer_after_insert ON orders; DROP FUNCTION record_compatibility_order_after_insert(); DROP TRIGGER orders_compatibility_writer_before_insert ON orders; DROP FUNCTION classify_compatibility_order_before_insert(); DROP TRIGGER order_current_owners_identity_immutable ON order_current_owners; DROP FUNCTION protect_order_current_owner(); DROP TRIGGER order_items_inventory_snapshot_immutable ON order_items; DROP FUNCTION protect_order_item_inventory_snapshot(); DROP TRIGGER order_workflow_migration_runs_no_delete ON order_workflow_migration_runs; DROP TRIGGER order_workflow_classifications_append_only ON order_workflow_classifications; DROP TRIGGER orders_workflow_immutable ON orders; DROP FUNCTION protect_append_only_checkout_prerequisite(); DROP FUNCTION protect_order_workflow_truth(); DROP TABLE order_workflow_classifications"
    )
