"""add hub quality persistence

Revision ID: a4e6c8f1b3d5
Revises: 9d3e5f7a1b2c
Create Date: 2026-07-24 20:36:52.389823

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a4e6c8f1b3d5"
down_revision: Union[str, None] = "9d3e5f7a1b2c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_inbound_transfers_hub_identity",
        "inbound_transfers",
        ["id", "cohort_id", "order_id", "vendor_id", "target_hub_id"],
    )
    op.create_unique_constraint(
        "uq_inbound_transfer_items_identity",
        "inbound_transfer_item_allocations",
        ["transfer_id", "order_item_id", "cohort_id", "order_id", "vendor_id"],
    )
    op.create_table(
        "hub_receipt_sessions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("inbound_transfer_id", sa.UUID(), nullable=False),
        sa.Column("cohort_id", sa.UUID(), nullable=False),
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column("vendor_id", sa.UUID(), nullable=False),
        sa.Column("hub_id", sa.UUID(), nullable=False),
        sa.Column("operator_id", sa.UUID(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=200), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "completed_at IS NULL OR completed_at >= started_at",
            name="ck_hub_receipt_sessions_time_order",
        ),
        sa.CheckConstraint(
            "idempotency_key = btrim(idempotency_key) AND length(idempotency_key) > 0",
            name="ck_hub_receipt_sessions_idempotency_canonical",
        ),
        sa.CheckConstraint(
            "version >= 1", name="ck_hub_receipt_sessions_version_positive"
        ),
        sa.ForeignKeyConstraint(
            ["inbound_transfer_id", "cohort_id", "order_id", "vendor_id", "hub_id"],
            [
                "inbound_transfers.id",
                "inbound_transfers.cohort_id",
                "inbound_transfers.order_id",
                "inbound_transfers.vendor_id",
                "inbound_transfers.target_hub_id",
            ],
            name="fk_hub_receipt_sessions_transfer_hub_identity",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(["operator_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "hub_id", "idempotency_key", name="uq_hub_receipt_sessions_idempotency"
        ),
        sa.UniqueConstraint(
            "id",
            "order_id",
            "vendor_id",
            "hub_id",
            name="uq_hub_receipt_sessions_evidence_identity",
        ),
        sa.UniqueConstraint(
            "id",
            "inbound_transfer_id",
            "cohort_id",
            "order_id",
            "vendor_id",
            "hub_id",
            name="uq_hub_receipt_sessions_identity",
        ),
    )
    op.create_table(
        "hub_qc_sessions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("receipt_session_id", sa.UUID(), nullable=False),
        sa.Column("inbound_transfer_id", sa.UUID(), nullable=False),
        sa.Column("cohort_id", sa.UUID(), nullable=False),
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column("vendor_id", sa.UUID(), nullable=False),
        sa.Column("hub_id", sa.UUID(), nullable=False),
        sa.Column("operator_id", sa.UUID(), nullable=False),
        sa.Column("source_command", sa.String(length=100), nullable=False),
        sa.Column("idempotency_key", sa.String(length=200), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("previous_session_id", sa.UUID(), nullable=True),
        sa.Column("remediation_id", sa.UUID(), nullable=True),
        sa.Column("state", sa.String(length=30), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(sequence = 1 AND previous_session_id IS NULL AND remediation_id IS NULL) OR (sequence > 1 AND previous_session_id IS NOT NULL AND remediation_id IS NOT NULL)",
            name="ck_hub_qc_sessions_reinspection_lineage",
        ),
        sa.CheckConstraint(
            "completed_at IS NULL OR completed_at >= started_at",
            name="ck_hub_qc_sessions_time_order",
        ),
        sa.CheckConstraint(
            "completed_at IS NULL OR started_at IS NOT NULL",
            name="ck_hub_qc_sessions_completion_started",
        ),
        sa.CheckConstraint(
            "sequence >= 1", name="ck_hub_qc_sessions_sequence_positive"
        ),
        sa.CheckConstraint(
            "source_command = btrim(source_command) AND length(source_command) > 0 AND "
            "idempotency_key = btrim(idempotency_key) AND length(idempotency_key) > 0",
            name="ck_hub_qc_sessions_command_identity_canonical",
        ),
        sa.CheckConstraint(
            "state IN ('qc_pending', 'qc_in_progress', 'qc_passed', 'qc_failed', "
            "'remediation', 'cancelled')",
            name="ck_hub_qc_sessions_state",
        ),
        sa.CheckConstraint("version >= 1", name="ck_hub_qc_sessions_version_positive"),
        sa.ForeignKeyConstraint(["operator_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["previous_session_id", "receipt_session_id"],
            ["hub_qc_sessions.id", "hub_qc_sessions.receipt_session_id"],
            name="fk_hub_qc_sessions_previous_identity",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            [
                "receipt_session_id",
                "inbound_transfer_id",
                "cohort_id",
                "order_id",
                "vendor_id",
                "hub_id",
            ],
            [
                "hub_receipt_sessions.id",
                "hub_receipt_sessions.inbound_transfer_id",
                "hub_receipt_sessions.cohort_id",
                "hub_receipt_sessions.order_id",
                "hub_receipt_sessions.vendor_id",
                "hub_receipt_sessions.hub_id",
            ],
            name="fk_hub_qc_sessions_receipt_identity",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "id",
            "receipt_session_id",
            "order_id",
            "vendor_id",
            "hub_id",
            name="uq_hub_qc_sessions_identity",
        ),
        sa.UniqueConstraint("previous_session_id", name="uq_hub_qc_sessions_previous"),
        sa.UniqueConstraint(
            "hub_id", "idempotency_key", name="uq_hub_qc_sessions_idempotency"
        ),
        sa.UniqueConstraint(
            "receipt_session_id", "sequence", name="uq_hub_qc_sessions_sequence"
        ),
        sa.UniqueConstraint(
            "id",
            "receipt_session_id",
            name="uq_hub_qc_sessions_previous_identity",
        ),
        sa.UniqueConstraint("remediation_id", name="uq_hub_qc_sessions_remediation"),
    )
    op.create_table(
        "hub_receipt_items",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("receipt_session_id", sa.UUID(), nullable=False),
        sa.Column("inbound_transfer_id", sa.UUID(), nullable=False),
        sa.Column("cohort_id", sa.UUID(), nullable=False),
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column("vendor_id", sa.UUID(), nullable=False),
        sa.Column("hub_id", sa.UUID(), nullable=False),
        sa.Column("order_item_id", sa.UUID(), nullable=False),
        sa.Column("expected_quantity", sa.Integer(), nullable=False),
        sa.Column("received_quantity", sa.Integer(), nullable=False),
        sa.Column("scan_identity", sa.String(length=200), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "expected_quantity > 0", name="ck_hub_receipt_items_expected_positive"
        ),
        sa.CheckConstraint(
            "received_quantity >= 0", name="ck_hub_receipt_items_received_nonnegative"
        ),
        sa.CheckConstraint(
            "scan_identity = btrim(scan_identity) AND length(scan_identity) > 0",
            name="ck_hub_receipt_items_scan_canonical",
        ),
        sa.ForeignKeyConstraint(
            [
                "inbound_transfer_id",
                "order_item_id",
                "cohort_id",
                "order_id",
                "vendor_id",
            ],
            [
                "inbound_transfer_item_allocations.transfer_id",
                "inbound_transfer_item_allocations.order_item_id",
                "inbound_transfer_item_allocations.cohort_id",
                "inbound_transfer_item_allocations.order_id",
                "inbound_transfer_item_allocations.vendor_id",
            ],
            name="fk_hub_receipt_items_transfer_allocation",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            [
                "receipt_session_id",
                "inbound_transfer_id",
                "cohort_id",
                "order_id",
                "vendor_id",
                "hub_id",
            ],
            [
                "hub_receipt_sessions.id",
                "hub_receipt_sessions.inbound_transfer_id",
                "hub_receipt_sessions.cohort_id",
                "hub_receipt_sessions.order_id",
                "hub_receipt_sessions.vendor_id",
                "hub_receipt_sessions.hub_id",
            ],
            name="fk_hub_receipt_items_session_identity",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "id",
            "receipt_session_id",
            "inbound_transfer_id",
            "cohort_id",
            "order_id",
            "vendor_id",
            "hub_id",
            "order_item_id",
            name="uq_hub_receipt_items_identity",
        ),
        sa.UniqueConstraint(
            "receipt_session_id", "order_item_id", name="uq_hub_receipt_items_item"
        ),
        sa.UniqueConstraint(
            "inbound_transfer_id", "scan_identity", name="uq_hub_receipt_items_scan"
        ),
    )
    op.create_table(
        "hub_discrepancies",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("receipt_session_id", sa.UUID(), nullable=False),
        sa.Column("receipt_item_id", sa.UUID(), nullable=False),
        sa.Column("inbound_transfer_id", sa.UUID(), nullable=False),
        sa.Column("cohort_id", sa.UUID(), nullable=False),
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column("vendor_id", sa.UUID(), nullable=False),
        sa.Column("hub_id", sa.UUID(), nullable=False),
        sa.Column("order_item_id", sa.UUID(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "shortage",
                "excess",
                "wrong_item",
                "damage",
                name="hub_discrepancy_type",
            ),
            nullable=False,
        ),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("observed_item_identity", sa.String(length=200), nullable=True),
        sa.Column("reason_code", sa.String(length=100), nullable=True),
        sa.Column("private_notes", sa.Text(), nullable=True),
        sa.Column(
            "quarantine_disposition",
            sa.Enum(
                "not_applicable",
                "quarantined",
                "return_to_vendor",
                "rework",
                "refund",
                "disposal",
                "investigation",
                name="hub_quarantine_disposition",
            ),
            server_default="not_applicable",
            nullable=False,
        ),
        sa.Column("recorded_by_id", sa.UUID(), nullable=False),
        sa.Column(
            "recorded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(type = 'shortage' AND quarantine_disposition = 'not_applicable') OR (type <> 'shortage' AND quarantine_disposition <> 'not_applicable')",
            name="ck_hub_discrepancies_quarantine_semantics",
        ),
        sa.CheckConstraint(
            "(type = 'wrong_item' AND observed_item_identity IS NOT NULL AND observed_item_identity = btrim(observed_item_identity) AND length(observed_item_identity) > 0) OR (type <> 'wrong_item' AND observed_item_identity IS NULL)",
            name="ck_hub_discrepancies_observed_identity_semantics",
        ),
        sa.CheckConstraint(
            "quantity > 0", name="ck_hub_discrepancies_quantity_positive"
        ),
        sa.ForeignKeyConstraint(
            [
                "receipt_item_id",
                "receipt_session_id",
                "inbound_transfer_id",
                "cohort_id",
                "order_id",
                "vendor_id",
                "hub_id",
                "order_item_id",
            ],
            [
                "hub_receipt_items.id",
                "hub_receipt_items.receipt_session_id",
                "hub_receipt_items.inbound_transfer_id",
                "hub_receipt_items.cohort_id",
                "hub_receipt_items.order_id",
                "hub_receipt_items.vendor_id",
                "hub_receipt_items.hub_id",
                "hub_receipt_items.order_item_id",
            ],
            name="fk_hub_discrepancies_receipt_item_identity",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(["recorded_by_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "id",
            "receipt_session_id",
            "order_id",
            "vendor_id",
            "hub_id",
            name="uq_hub_discrepancies_identity",
        ),
    )
    op.create_table(
        "hub_qc_inspections",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("qc_session_id", sa.UUID(), nullable=False),
        sa.Column("receipt_session_id", sa.UUID(), nullable=False),
        sa.Column("inbound_transfer_id", sa.UUID(), nullable=False),
        sa.Column("cohort_id", sa.UUID(), nullable=False),
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column("vendor_id", sa.UUID(), nullable=False),
        sa.Column("hub_id", sa.UUID(), nullable=False),
        sa.Column("receipt_item_id", sa.UUID(), nullable=False),
        sa.Column("order_item_id", sa.UUID(), nullable=False),
        sa.Column(
            "decision",
            sa.Enum("pending", "pass", "fail", "rejected", name="hub_qc_decision"),
            nullable=False,
        ),
        sa.Column("inspected_quantity", sa.Integer(), nullable=False),
        sa.Column("reason_code", sa.String(length=100), nullable=True),
        sa.Column("private_notes", sa.Text(), nullable=True),
        sa.Column(
            "quarantine_disposition",
            sa.Enum(
                "not_applicable",
                "quarantined",
                "return_to_vendor",
                "rework",
                "refund",
                "disposal",
                "investigation",
                name="hub_quarantine_disposition",
            ),
            server_default="not_applicable",
            nullable=False,
        ),
        sa.Column(
            "inspected_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(decision IN ('fail', 'rejected') AND reason_code IS NOT NULL AND length(btrim(reason_code)) > 0 AND quarantine_disposition <> 'not_applicable') OR (decision NOT IN ('fail', 'rejected') AND quarantine_disposition = 'not_applicable')",
            name="ck_hub_qc_inspections_decision_semantics",
        ),
        sa.CheckConstraint(
            "inspected_quantity > 0", name="ck_hub_qc_inspections_quantity_positive"
        ),
        sa.CheckConstraint(
            "version >= 1", name="ck_hub_qc_inspections_version_positive"
        ),
        sa.ForeignKeyConstraint(
            ["qc_session_id", "receipt_session_id", "order_id", "vendor_id", "hub_id"],
            [
                "hub_qc_sessions.id",
                "hub_qc_sessions.receipt_session_id",
                "hub_qc_sessions.order_id",
                "hub_qc_sessions.vendor_id",
                "hub_qc_sessions.hub_id",
            ],
            name="fk_hub_qc_inspections_session_identity",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            [
                "receipt_item_id",
                "receipt_session_id",
                "inbound_transfer_id",
                "cohort_id",
                "order_id",
                "vendor_id",
                "hub_id",
                "order_item_id",
            ],
            [
                "hub_receipt_items.id",
                "hub_receipt_items.receipt_session_id",
                "hub_receipt_items.inbound_transfer_id",
                "hub_receipt_items.cohort_id",
                "hub_receipt_items.order_id",
                "hub_receipt_items.vendor_id",
                "hub_receipt_items.hub_id",
                "hub_receipt_items.order_item_id",
            ],
            name="fk_hub_qc_inspections_receipt_item_identity",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "id",
            "qc_session_id",
            "receipt_session_id",
            "order_id",
            "vendor_id",
            "hub_id",
            name="uq_hub_qc_inspections_identity",
        ),
        sa.UniqueConstraint(
            "qc_session_id", "receipt_item_id", name="uq_hub_qc_inspections_item"
        ),
        sa.UniqueConstraint(
            "id",
            "receipt_session_id",
            "order_id",
            "vendor_id",
            "hub_id",
            name="uq_hub_qc_inspections_evidence_identity",
        ),
    )
    op.create_table(
        "hub_evidence",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("receipt_session_id", sa.UUID(), nullable=False),
        sa.Column("inspection_id", sa.UUID(), nullable=True),
        sa.Column("discrepancy_id", sa.UUID(), nullable=True),
        sa.Column("remediation_id", sa.UUID(), nullable=True),
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column("vendor_id", sa.UUID(), nullable=False),
        sa.Column("hub_id", sa.UUID(), nullable=False),
        sa.Column(
            "purpose",
            sa.Enum(
                "hub_receipt",
                "discrepancy",
                "qc_inspection",
                "remediation",
                name="hub_evidence_purpose",
            ),
            nullable=False,
        ),
        sa.Column("access_scope", sa.String(length=100), nullable=False),
        sa.Column("storage_reference", sa.String(length=500), nullable=False),
        sa.Column("integrity_hash", sa.String(length=64), nullable=False),
        sa.Column("content_type", sa.String(length=100), nullable=False),
        sa.Column("byte_size", sa.Integer(), nullable=False),
        sa.Column("retention_until", sa.DateTime(timezone=True), nullable=False),
        sa.Column("legal_hold", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "retention_policy_updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "integrity_hash ~ '^[0-9a-f]{64}$'", name="ck_hub_evidence_integrity_hash"
        ),
        sa.CheckConstraint(
            "storage_reference = btrim(storage_reference) AND storage_reference ~ '^private/[^/?#]+(/[^/?#]+)*$' AND strpos(storage_reference, chr(92)) = 0 AND storage_reference !~ '(^|/)[.]{1,2}(/|$)'",
            name="ck_hub_evidence_private_reference",
        ),
        sa.CheckConstraint(
            "access_scope = 'hub_quality_private'",
            name="ck_hub_evidence_access_scope",
        ),
        sa.CheckConstraint("byte_size > 0", name="ck_hub_evidence_byte_size_positive"),
        sa.CheckConstraint(
            "retention_until > created_at", name="ck_hub_evidence_retention_future"
        ),
        sa.CheckConstraint(
            "retention_policy_updated_at >= created_at",
            name="ck_hub_evidence_policy_timestamp_order",
        ),
        sa.CheckConstraint(
            "(purpose = 'hub_receipt' AND inspection_id IS NULL AND discrepancy_id IS NULL AND remediation_id IS NULL) OR (purpose = 'discrepancy' AND discrepancy_id IS NOT NULL AND inspection_id IS NULL AND remediation_id IS NULL) OR (purpose = 'qc_inspection' AND inspection_id IS NOT NULL AND discrepancy_id IS NULL AND remediation_id IS NULL) OR (purpose = 'remediation' AND remediation_id IS NOT NULL AND inspection_id IS NULL AND discrepancy_id IS NULL)",
            name="ck_hub_evidence_purpose_subject",
        ),
        sa.ForeignKeyConstraint(["created_by_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["discrepancy_id", "receipt_session_id", "order_id", "vendor_id", "hub_id"],
            [
                "hub_discrepancies.id",
                "hub_discrepancies.receipt_session_id",
                "hub_discrepancies.order_id",
                "hub_discrepancies.vendor_id",
                "hub_discrepancies.hub_id",
            ],
            name="fk_hub_evidence_discrepancy_identity",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["inspection_id", "receipt_session_id", "order_id", "vendor_id", "hub_id"],
            [
                "hub_qc_inspections.id",
                "hub_qc_inspections.receipt_session_id",
                "hub_qc_inspections.order_id",
                "hub_qc_inspections.vendor_id",
                "hub_qc_inspections.hub_id",
            ],
            name="fk_hub_evidence_inspection_identity",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["receipt_session_id", "order_id", "vendor_id", "hub_id"],
            [
                "hub_receipt_sessions.id",
                "hub_receipt_sessions.order_id",
                "hub_receipt_sessions.vendor_id",
                "hub_receipt_sessions.hub_id",
            ],
            name="fk_hub_evidence_receipt_identity",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "storage_reference", name="uq_hub_evidence_storage_reference"
        ),
    )
    op.create_table(
        "hub_evidence_retention_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("evidence_id", sa.UUID(), nullable=False),
        sa.Column("actor_id", sa.UUID(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("reason", sa.String(length=500), nullable=False),
        sa.Column("previous_legal_hold", sa.Boolean(), nullable=False),
        sa.Column("resulting_legal_hold", sa.Boolean(), nullable=False),
        sa.Column(
            "previous_retention_until", sa.DateTime(timezone=True), nullable=False
        ),
        sa.Column(
            "resulting_retention_until", sa.DateTime(timezone=True), nullable=False
        ),
        sa.CheckConstraint(
            "reason = btrim(reason) AND length(reason) > 0",
            name="ck_hub_evidence_retention_events_reason_canonical",
        ),
        sa.CheckConstraint(
            "previous_legal_hold IS DISTINCT FROM resulting_legal_hold OR "
            "previous_retention_until IS DISTINCT FROM resulting_retention_until",
            name="ck_hub_evidence_retention_events_changes_policy",
        ),
        sa.ForeignKeyConstraint(["actor_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["evidence_id"], ["hub_evidence.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "hub_remediations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("failed_inspection_id", sa.UUID(), nullable=False),
        sa.Column("qc_session_id", sa.UUID(), nullable=False),
        sa.Column("receipt_session_id", sa.UUID(), nullable=False),
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column("vendor_id", sa.UUID(), nullable=False),
        sa.Column("hub_id", sa.UUID(), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("approved_by_id", sa.UUID(), nullable=True),
        sa.Column(
            "action",
            sa.Enum(
                "rework",
                "return_to_vendor",
                "refund",
                "disposal",
                "investigate",
                name="hub_remediation_action",
            ),
            nullable=False,
        ),
        sa.Column(
            "state",
            sa.Enum(
                "pending_approval",
                "approved",
                "in_progress",
                "completed",
                "cancelled",
                name="hub_remediation_state",
            ),
            nullable=False,
        ),
        sa.Column(
            "disposition",
            sa.Enum(
                "not_applicable",
                "quarantined",
                "return_to_vendor",
                "rework",
                "refund",
                "disposal",
                "investigation",
                name="hub_quarantine_disposition",
            ),
            nullable=False,
        ),
        sa.Column("private_notes", sa.Text(), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "disposition <> 'not_applicable'",
            name="ck_hub_remediations_disposition_required",
        ),
        sa.CheckConstraint(
            "(state IN ('pending_approval', 'cancelled') AND approved_at IS NULL AND approved_by_id IS NULL) OR (state NOT IN ('pending_approval', 'cancelled') AND approved_at IS NOT NULL AND approved_by_id IS NOT NULL)",
            name="ck_hub_remediations_approval_audit",
        ),
        sa.CheckConstraint(
            "(state = 'completed' AND completed_at IS NOT NULL) OR (state <> 'completed' AND completed_at IS NULL)",
            name="ck_hub_remediations_completed_timestamp",
        ),
        sa.CheckConstraint(
            "completed_at IS NULL OR approved_at IS NOT NULL",
            name="ck_hub_remediations_completion_approved",
        ),
        sa.CheckConstraint(
            "completed_at IS NULL OR completed_at >= approved_at",
            name="ck_hub_remediations_time_order",
        ),
        sa.CheckConstraint("version >= 1", name="ck_hub_remediations_version_positive"),
        sa.ForeignKeyConstraint(
            [
                "failed_inspection_id",
                "qc_session_id",
                "receipt_session_id",
                "order_id",
                "vendor_id",
                "hub_id",
            ],
            [
                "hub_qc_inspections.id",
                "hub_qc_inspections.qc_session_id",
                "hub_qc_inspections.receipt_session_id",
                "hub_qc_inspections.order_id",
                "hub_qc_inspections.vendor_id",
                "hub_qc_inspections.hub_id",
            ],
            name="fk_hub_remediations_failed_inspection_identity",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["approved_by_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "failed_inspection_id", name="uq_hub_remediations_failed_inspection"
        ),
        sa.UniqueConstraint(
            "id",
            "receipt_session_id",
            "order_id",
            "vendor_id",
            "hub_id",
            name="uq_hub_remediations_identity",
        ),
    )
    op.create_foreign_key(
        "fk_hub_qc_sessions_remediation_identity",
        "hub_qc_sessions",
        "hub_remediations",
        ["remediation_id", "receipt_session_id", "order_id", "vendor_id", "hub_id"],
        ["id", "receipt_session_id", "order_id", "vendor_id", "hub_id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        "fk_hub_evidence_remediation_identity",
        "hub_evidence",
        "hub_remediations",
        ["remediation_id", "receipt_session_id", "order_id", "vendor_id", "hub_id"],
        ["id", "receipt_session_id", "order_id", "vendor_id", "hub_id"],
        ondelete="RESTRICT",
    )
    op.execute(
        """
        CREATE FUNCTION reject_completed_hub_receipt_update() RETURNS trigger AS $$
        BEGIN
            IF TG_OP = 'INSERT' THEN
                IF NEW.completed_at IS NOT NULL THEN
                    RAISE EXCEPTION USING ERRCODE = '23514',
                        MESSAGE = 'receipt sessions must start incomplete';
                END IF;
                RETURN NEW;
            END IF;
            IF NEW.completed_at IS NOT NULL AND NEW.completed_at > clock_timestamp() THEN
                RAISE EXCEPTION USING ERRCODE = '23514',
                    MESSAGE = 'receipt completion timestamp cannot be future-dated';
            END IF;
            IF OLD.completed_at IS NOT NULL THEN
                RAISE EXCEPTION USING ERRCODE = '23514',
                    MESSAGE = 'completed receipt sessions are immutable';
            END IF;
            IF NEW.id IS DISTINCT FROM OLD.id
               OR NEW.inbound_transfer_id IS DISTINCT FROM OLD.inbound_transfer_id
               OR NEW.cohort_id IS DISTINCT FROM OLD.cohort_id
               OR NEW.order_id IS DISTINCT FROM OLD.order_id
               OR NEW.vendor_id IS DISTINCT FROM OLD.vendor_id
               OR NEW.hub_id IS DISTINCT FROM OLD.hub_id
               OR NEW.idempotency_key IS DISTINCT FROM OLD.idempotency_key
               OR NEW.operator_id IS DISTINCT FROM OLD.operator_id
               OR NEW.started_at IS DISTINCT FROM OLD.started_at
               OR NEW.created_at IS DISTINCT FROM OLD.created_at THEN
                RAISE EXCEPTION USING ERRCODE = '23514',
                    MESSAGE = 'receipt session identity is immutable';
            END IF;
            RETURN NEW;
        END; $$ LANGUAGE plpgsql
        """
    )
    op.execute(
        """CREATE TRIGGER tr_hub_receipt_sessions_completed_immutable
        BEFORE INSERT OR UPDATE ON hub_receipt_sessions
        FOR EACH ROW EXECUTE FUNCTION reject_completed_hub_receipt_update()"""
    )
    op.execute(
        """
        CREATE FUNCTION validate_hub_receipt_item_quantity() RETURNS trigger AS $$
        DECLARE allocated integer; already_received integer; receipt_completed timestamptz;
                max_inspected integer;
        BEGIN
            IF TG_OP = 'UPDATE' AND (
                NEW.id IS DISTINCT FROM OLD.id
                OR NEW.receipt_session_id IS DISTINCT FROM OLD.receipt_session_id
                OR NEW.inbound_transfer_id IS DISTINCT FROM OLD.inbound_transfer_id
                OR NEW.cohort_id IS DISTINCT FROM OLD.cohort_id
                OR NEW.order_id IS DISTINCT FROM OLD.order_id
                OR NEW.vendor_id IS DISTINCT FROM OLD.vendor_id
                OR NEW.hub_id IS DISTINCT FROM OLD.hub_id
                OR NEW.order_item_id IS DISTINCT FROM OLD.order_item_id
                OR NEW.scan_identity IS DISTINCT FROM OLD.scan_identity
            ) THEN
                RAISE EXCEPTION USING ERRCODE = '23514',
                    MESSAGE = 'receipt item aggregate identity is immutable';
            END IF;
            SELECT completed_at INTO receipt_completed
            FROM hub_receipt_sessions WHERE id = NEW.receipt_session_id FOR UPDATE;
            IF receipt_completed IS NOT NULL THEN
                RAISE EXCEPTION USING ERRCODE = '23514',
                    MESSAGE = 'completed receipt sessions are immutable';
            END IF;
            SELECT allocated_quantity INTO allocated
            FROM inbound_transfer_item_allocations
            WHERE transfer_id = NEW.inbound_transfer_id
              AND order_item_id = NEW.order_item_id
            FOR UPDATE;
            IF allocated IS NULL OR NEW.expected_quantity <> allocated THEN
                RAISE EXCEPTION USING ERRCODE = '23514',
                    MESSAGE = 'receipt expected quantity must equal transfer allocation';
            END IF;
            SELECT COALESCE(SUM(received_quantity), 0) INTO already_received
            FROM hub_receipt_items
            WHERE inbound_transfer_id = NEW.inbound_transfer_id
              AND order_item_id = NEW.order_item_id
              AND id <> NEW.id;
            IF already_received + NEW.received_quantity > allocated THEN
                RAISE EXCEPTION USING ERRCODE = '23514',
                    MESSAGE = 'cumulative received quantity exceeds transfer allocation';
            END IF;
            IF TG_OP = 'UPDATE' THEN
                IF (NEW.expected_quantity IS DISTINCT FROM OLD.expected_quantity
                    OR NEW.received_quantity IS DISTINCT FROM OLD.received_quantity)
                   AND EXISTS (
                       SELECT 1 FROM hub_discrepancies WHERE receipt_item_id = OLD.id
                   ) THEN
                    RAISE EXCEPTION USING ERRCODE = '23514',
                        MESSAGE = 'receipt quantity is frozen after discrepancy';
                END IF;
                SELECT COALESCE(MAX(inspected_quantity), 0) INTO max_inspected
                FROM hub_qc_inspections WHERE receipt_item_id = NEW.id;
                IF NEW.received_quantity < max_inspected THEN
                    RAISE EXCEPTION USING ERRCODE = '23514',
                        MESSAGE = 'received quantity cannot drop below inspected quantity';
                END IF;
            END IF;
            RETURN NEW;
        END; $$ LANGUAGE plpgsql
    """
    )
    op.execute(
        """
        CREATE TRIGGER tr_hub_receipt_items_quantity_safe
        BEFORE INSERT OR UPDATE ON hub_receipt_items
        FOR EACH ROW EXECUTE FUNCTION validate_hub_receipt_item_quantity()
    """
    )
    op.execute(
        """
        CREATE FUNCTION validate_hub_qc_inspection_quantity() RETURNS trigger AS $$
        DECLARE received integer;
        BEGIN
            SELECT received_quantity INTO received
            FROM hub_receipt_items
            WHERE id = NEW.receipt_item_id
            FOR UPDATE;
            IF received IS NULL OR NEW.inspected_quantity > received THEN
                RAISE EXCEPTION USING ERRCODE = '23514',
                    MESSAGE = 'inspection quantity exceeds received quantity';
            END IF;
            RETURN NEW;
        END; $$ LANGUAGE plpgsql
    """
    )
    op.execute(
        """
        CREATE TRIGGER tr_hub_qc_inspections_quantity_safe
        BEFORE INSERT OR UPDATE ON hub_qc_inspections
        FOR EACH ROW EXECUTE FUNCTION validate_hub_qc_inspection_quantity()
    """
    )
    op.execute(
        """
        CREATE FUNCTION validate_hub_qc_reinspection_lineage() RETURNS trigger AS $$
        DECLARE previous_sequence integer; previous_state varchar; previous_completed timestamptz;
                remediation_session uuid; remediation_receipt uuid; remediation_state hub_remediation_state;
                remediation_completed timestamptz;
        BEGIN
            IF NEW.sequence > 1 THEN
                SELECT qc_session_id, receipt_session_id, state, completed_at
                  INTO remediation_session, remediation_receipt, remediation_state, remediation_completed
                  FROM hub_remediations WHERE id = NEW.remediation_id FOR UPDATE;
                IF remediation_session IS DISTINCT FROM NEW.previous_session_id
                   OR remediation_receipt IS DISTINCT FROM NEW.receipt_session_id
                   OR remediation_state IS DISTINCT FROM 'completed' THEN
                    RAISE EXCEPTION USING ERRCODE = '23514',
                        MESSAGE = 'reinspection requires completed remediation for the previous QC session';
                END IF;
                IF remediation_completed IS NULL OR NEW.started_at < remediation_completed THEN
                    RAISE EXCEPTION USING ERRCODE = '23514',
                        MESSAGE = 'reinspection must start after remediation completion';
                END IF;
                SELECT sequence, state, completed_at
                  INTO previous_sequence, previous_state, previous_completed
                  FROM hub_qc_sessions
                 WHERE id = NEW.previous_session_id
                   AND receipt_session_id = NEW.receipt_session_id
                 FOR UPDATE;
                IF previous_sequence IS NULL OR previous_sequence <> NEW.sequence - 1 THEN
                    RAISE EXCEPTION USING ERRCODE = '23514',
                        MESSAGE = 'reinspection must follow the immediately previous QC sequence';
                END IF;
                IF previous_state <> 'qc_failed' OR previous_completed IS NULL THEN
                    RAISE EXCEPTION USING ERRCODE = '23514',
                        MESSAGE = 'reinspection requires a completed failed previous QC session';
                END IF;
            END IF;
            RETURN NEW;
        END; $$ LANGUAGE plpgsql
        """
    )
    op.execute(
        """CREATE TRIGGER tr_hub_qc_sessions_reinspection_lineage
        BEFORE INSERT ON hub_qc_sessions
        FOR EACH ROW EXECUTE FUNCTION validate_hub_qc_reinspection_lineage()"""
    )
    op.execute(
        """
        CREATE FUNCTION reject_completed_hub_qc_update() RETURNS trigger AS $$
        DECLARE qc_completed timestamptz; receipt_completed timestamptz;
        BEGIN
            IF TG_TABLE_NAME = 'hub_qc_sessions' THEN
                IF TG_OP = 'INSERT' THEN
                    IF NEW.completed_at IS NOT NULL THEN
                        RAISE EXCEPTION USING ERRCODE = '23514',
                            MESSAGE = 'QC sessions must start incomplete';
                    END IF;
                    IF NEW.state IN ('qc_passed', 'qc_failed') THEN
                        RAISE EXCEPTION USING ERRCODE = '23514',
                            MESSAGE = 'terminal QC state requires completion';
                    END IF;
                    RETURN NEW;
                END IF;
                IF OLD.completed_at IS NOT NULL THEN
                    RAISE EXCEPTION USING ERRCODE = '23514',
                        MESSAGE = 'completed QC sessions are immutable';
                END IF;
                IF NEW.completed_at IS NOT NULL AND NEW.completed_at > clock_timestamp() THEN
                    RAISE EXCEPTION USING ERRCODE = '23514',
                        MESSAGE = 'QC completion timestamp cannot be future-dated';
                END IF;
                IF NEW.id IS DISTINCT FROM OLD.id
                   OR NEW.receipt_session_id IS DISTINCT FROM OLD.receipt_session_id
                   OR NEW.inbound_transfer_id IS DISTINCT FROM OLD.inbound_transfer_id
                   OR NEW.cohort_id IS DISTINCT FROM OLD.cohort_id
                   OR NEW.order_id IS DISTINCT FROM OLD.order_id
                   OR NEW.vendor_id IS DISTINCT FROM OLD.vendor_id
                   OR NEW.hub_id IS DISTINCT FROM OLD.hub_id
                   OR NEW.operator_id IS DISTINCT FROM OLD.operator_id
                   OR NEW.source_command IS DISTINCT FROM OLD.source_command
                   OR NEW.idempotency_key IS DISTINCT FROM OLD.idempotency_key
                   OR NEW.sequence IS DISTINCT FROM OLD.sequence
                   OR NEW.previous_session_id IS DISTINCT FROM OLD.previous_session_id
                   OR NEW.remediation_id IS DISTINCT FROM OLD.remediation_id
                   OR NEW.started_at IS DISTINCT FROM OLD.started_at THEN
                    RAISE EXCEPTION USING ERRCODE = '23514',
                        MESSAGE = 'QC session aggregate lineage is immutable';
                END IF;
                IF NEW.state IS DISTINCT FROM OLD.state AND NOT (
                    (OLD.state = 'qc_pending' AND NEW.state = 'qc_in_progress') OR
                    (OLD.state = 'qc_in_progress' AND NEW.state IN ('qc_passed', 'qc_failed'))
                ) THEN
                    RAISE EXCEPTION USING ERRCODE = '23514',
                        MESSAGE = 'illegal QC state transition';
                END IF;
                IF NEW.state IN ('qc_passed', 'qc_failed') AND NEW.completed_at IS NULL THEN
                    RAISE EXCEPTION USING ERRCODE = '23514',
                        MESSAGE = 'terminal QC state requires completion';
                END IF;
                IF NEW.state NOT IN ('qc_passed', 'qc_failed') AND NEW.completed_at IS NOT NULL THEN
                    RAISE EXCEPTION USING ERRCODE = '23514',
                        MESSAGE = 'QC completion requires a terminal state';
                END IF;
                IF OLD.completed_at IS NULL AND NEW.completed_at IS NOT NULL THEN
                    IF NEW.state NOT IN ('qc_passed', 'qc_failed') THEN
                        RAISE EXCEPTION USING ERRCODE = '23514',
                            MESSAGE = 'QC completion requires a terminal state';
                    END IF;
                    SELECT completed_at INTO receipt_completed FROM hub_receipt_sessions
                    WHERE id = NEW.receipt_session_id FOR UPDATE;
                    IF receipt_completed IS NULL THEN
                        RAISE EXCEPTION USING ERRCODE = '23514',
                            MESSAGE = 'QC completion requires a completed receipt session';
                    END IF;
                    IF NEW.state = 'qc_passed' AND (
                        NOT EXISTS (
                            SELECT 1 FROM hub_receipt_items
                            WHERE receipt_session_id = NEW.receipt_session_id
                        ) OR EXISTS (
                            SELECT 1 FROM hub_receipt_items item
                            WHERE item.receipt_session_id = NEW.receipt_session_id
                              AND NOT EXISTS (
                                  SELECT 1 FROM hub_qc_inspections inspection
                                  WHERE inspection.qc_session_id = NEW.id
                                    AND inspection.receipt_item_id = item.id
                                    AND inspection.decision = 'pass'
                              )
                        )
                    ) THEN
                        RAISE EXCEPTION USING ERRCODE = '23514',
                            MESSAGE = 'passed QC completion requires all receipt items to pass';
                    END IF;
                    IF NEW.state = 'qc_failed' AND NOT EXISTS (
                        SELECT 1 FROM hub_qc_inspections
                        WHERE qc_session_id = NEW.id AND decision IN ('fail', 'rejected')
                    ) THEN
                        RAISE EXCEPTION USING ERRCODE = '23514',
                            MESSAGE = 'failed QC completion requires a failed or rejected inspection';
                    END IF;
                END IF;
            ELSE
                IF TG_OP = 'UPDATE' AND (
                    NEW.id IS DISTINCT FROM OLD.id
                    OR NEW.qc_session_id IS DISTINCT FROM OLD.qc_session_id
                    OR NEW.receipt_session_id IS DISTINCT FROM OLD.receipt_session_id
                    OR NEW.inbound_transfer_id IS DISTINCT FROM OLD.inbound_transfer_id
                    OR NEW.cohort_id IS DISTINCT FROM OLD.cohort_id
                    OR NEW.order_id IS DISTINCT FROM OLD.order_id
                    OR NEW.vendor_id IS DISTINCT FROM OLD.vendor_id
                    OR NEW.hub_id IS DISTINCT FROM OLD.hub_id
                    OR NEW.receipt_item_id IS DISTINCT FROM OLD.receipt_item_id
                    OR NEW.order_item_id IS DISTINCT FROM OLD.order_item_id
                ) THEN
                    RAISE EXCEPTION USING ERRCODE = '23514',
                        MESSAGE = 'QC inspection aggregate identity is immutable';
                END IF;
                SELECT completed_at INTO qc_completed FROM hub_qc_sessions
                 WHERE id = NEW.qc_session_id FOR UPDATE;
                IF qc_completed IS NOT NULL THEN
                    RAISE EXCEPTION USING ERRCODE = '23514',
                        MESSAGE = 'inspections in completed QC sessions are immutable';
                END IF;
                IF TG_OP = 'UPDATE' AND EXISTS (
                    SELECT 1 FROM hub_remediations
                    WHERE failed_inspection_id = OLD.id
                ) THEN
                    RAISE EXCEPTION USING ERRCODE = '23514',
                        MESSAGE = 'remediated inspections are immutable';
                END IF;
            END IF;
            RETURN NEW;
        END; $$ LANGUAGE plpgsql
        """
    )
    op.execute(
        """CREATE TRIGGER tr_hub_qc_sessions_completed_immutable
        BEFORE INSERT OR UPDATE ON hub_qc_sessions
        FOR EACH ROW EXECUTE FUNCTION reject_completed_hub_qc_update()"""
    )
    op.execute(
        """CREATE TRIGGER tr_hub_qc_inspections_completed_immutable
        BEFORE INSERT OR UPDATE ON hub_qc_inspections
        FOR EACH ROW EXECUTE FUNCTION reject_completed_hub_qc_update()"""
    )
    op.execute(
        """
        CREATE FUNCTION validate_hub_remediation_invariants() RETURNS trigger AS $$
        DECLARE inspection_decision hub_qc_decision; parent_qc_state varchar;
                parent_qc_completed timestamptz;
        BEGIN
            IF TG_OP = 'INSERT' AND NEW.state IS DISTINCT FROM 'pending_approval' THEN
                RAISE EXCEPTION USING ERRCODE = '23514',
                    MESSAGE = 'remediations must start pending';
            END IF;
            IF NEW.approved_at IS NOT NULL AND (
                NEW.approved_at < NEW.created_at OR NEW.approved_at > clock_timestamp()
            ) THEN
                RAISE EXCEPTION USING ERRCODE = '23514',
                    MESSAGE = 'approval timestamp must follow creation and not be future-dated';
            END IF;
            IF NEW.completed_at IS NOT NULL AND (
                NEW.approved_at IS NULL OR NEW.completed_at < NEW.approved_at
                OR NEW.completed_at > clock_timestamp()
            ) THEN
                RAISE EXCEPTION USING ERRCODE = '23514',
                    MESSAGE = 'completion timestamp must follow approval and not be future-dated';
            END IF;
            IF TG_OP = 'UPDATE' THEN
                IF OLD.state IN ('completed', 'cancelled') OR EXISTS (
                    SELECT 1 FROM hub_qc_sessions WHERE remediation_id = OLD.id
                ) THEN
                    RAISE EXCEPTION USING ERRCODE = '23514',
                        MESSAGE = 'terminal or consumed remediation is immutable';
                END IF;
                IF NEW.id IS DISTINCT FROM OLD.id
                   OR NEW.failed_inspection_id IS DISTINCT FROM OLD.failed_inspection_id
                   OR NEW.qc_session_id IS DISTINCT FROM OLD.qc_session_id
                   OR NEW.receipt_session_id IS DISTINCT FROM OLD.receipt_session_id
                   OR NEW.order_id IS DISTINCT FROM OLD.order_id
                   OR NEW.vendor_id IS DISTINCT FROM OLD.vendor_id
                   OR NEW.hub_id IS DISTINCT FROM OLD.hub_id
                   OR NEW.created_at IS DISTINCT FROM OLD.created_at THEN
                    RAISE EXCEPTION USING ERRCODE = '23514',
                        MESSAGE = 'remediation identity is immutable';
                END IF;
                IF NEW.state IS DISTINCT FROM OLD.state AND NOT (
                    (OLD.state = 'pending_approval' AND NEW.state = 'approved'
                     AND NEW.approved_by_id IS NOT NULL AND NEW.approved_at IS NOT NULL)
                    OR (OLD.state = 'pending_approval' AND NEW.state = 'cancelled')
                    OR (OLD.state = 'approved' AND NEW.state = 'in_progress')
                    OR (OLD.state = 'in_progress' AND NEW.state = 'completed'
                        AND NEW.completed_at IS NOT NULL)
                ) THEN
                    RAISE EXCEPTION USING ERRCODE = '23514',
                        MESSAGE = 'illegal remediation state transition';
                END IF;
                IF OLD.state IN ('approved', 'in_progress') AND (
                    NEW.owner_id IS DISTINCT FROM OLD.owner_id
                    OR NEW.action IS DISTINCT FROM OLD.action
                    OR NEW.disposition IS DISTINCT FROM OLD.disposition
                    OR NEW.approved_by_id IS DISTINCT FROM OLD.approved_by_id
                    OR NEW.approved_at IS DISTINCT FROM OLD.approved_at
                ) THEN
                    RAISE EXCEPTION USING ERRCODE = '23514',
                        MESSAGE = 'approved remediation terms and audit are immutable';
                END IF;
                IF NEW.completed_at IS DISTINCT FROM OLD.completed_at
                   AND NOT (OLD.state = 'in_progress' AND NEW.state = 'completed'
                            AND NEW.completed_at IS NOT NULL) THEN
                    RAISE EXCEPTION USING ERRCODE = '23514',
                        MESSAGE = 'completion timestamp requires completion transition';
                END IF;
            END IF;
            SELECT state, completed_at INTO parent_qc_state, parent_qc_completed
            FROM hub_qc_sessions WHERE id = NEW.qc_session_id FOR UPDATE;
            IF NEW.state IN ('approved', 'in_progress', 'completed') THEN
                IF parent_qc_state IS DISTINCT FROM 'qc_failed' OR parent_qc_completed IS NULL THEN
                    RAISE EXCEPTION USING ERRCODE = '23514',
                        MESSAGE = 'remediation approval requires a completed failed QC session';
                END IF;
                IF NEW.approved_at < parent_qc_completed THEN
                    RAISE EXCEPTION USING ERRCODE = '23514',
                        MESSAGE = 'remediation approval must follow QC completion';
                END IF;
            END IF;
            SELECT decision INTO inspection_decision
            FROM hub_qc_inspections
            WHERE id = NEW.failed_inspection_id AND qc_session_id = NEW.qc_session_id;
            IF inspection_decision IS NULL OR inspection_decision NOT IN ('fail', 'rejected') THEN
                RAISE EXCEPTION USING ERRCODE = '23514',
                    MESSAGE = 'remediation requires a failed or rejected inspection';
            END IF;
            RETURN NEW;
        END; $$ LANGUAGE plpgsql
        """
    )
    op.execute(
        """CREATE TRIGGER tr_hub_remediations_invariants
        BEFORE INSERT OR UPDATE ON hub_remediations
        FOR EACH ROW EXECUTE FUNCTION validate_hub_remediation_invariants()"""
    )
    op.execute(
        """
        CREATE OR REPLACE FUNCTION validate_hub_evidence_update() RETURNS trigger AS $$
        BEGIN
            IF NEW.id IS DISTINCT FROM OLD.id
               OR NEW.receipt_session_id IS DISTINCT FROM OLD.receipt_session_id
               OR NEW.inspection_id IS DISTINCT FROM OLD.inspection_id
               OR NEW.discrepancy_id IS DISTINCT FROM OLD.discrepancy_id
               OR NEW.remediation_id IS DISTINCT FROM OLD.remediation_id
               OR NEW.order_id IS DISTINCT FROM OLD.order_id
               OR NEW.vendor_id IS DISTINCT FROM OLD.vendor_id
               OR NEW.hub_id IS DISTINCT FROM OLD.hub_id
               OR NEW.purpose IS DISTINCT FROM OLD.purpose
               OR NEW.access_scope IS DISTINCT FROM OLD.access_scope
               OR NEW.storage_reference IS DISTINCT FROM OLD.storage_reference
               OR NEW.integrity_hash IS DISTINCT FROM OLD.integrity_hash
               OR NEW.content_type IS DISTINCT FROM OLD.content_type
               OR NEW.byte_size IS DISTINCT FROM OLD.byte_size
               OR NEW.created_by_id IS DISTINCT FROM OLD.created_by_id
               OR NEW.created_at IS DISTINCT FROM OLD.created_at
               OR (NEW.legal_hold IS NOT DISTINCT FROM OLD.legal_hold
                   AND NEW.retention_until IS NOT DISTINCT FROM OLD.retention_until
                   AND NEW.retention_policy_updated_at IS NOT DISTINCT FROM OLD.retention_policy_updated_at) THEN
                RAISE EXCEPTION USING ERRCODE = '23514',
                    MESSAGE = 'hub quality audit records are immutable';
            END IF;
            IF pg_trigger_depth() <> 2 THEN
                RAISE EXCEPTION USING ERRCODE = '23514',
                    MESSAGE = 'evidence policy changes require a retention event';
            END IF;
            RETURN NEW;
        END; $$ LANGUAGE plpgsql
        """
    )
    op.execute(
        """CREATE TRIGGER tr_hub_evidence_update_restricted
        BEFORE UPDATE ON hub_evidence
        FOR EACH ROW EXECUTE FUNCTION validate_hub_evidence_update()"""
    )
    op.execute(
        """
        CREATE OR REPLACE FUNCTION validate_hub_evidence_retention_event() RETURNS trigger AS $$
        DECLARE current_hold boolean; current_retention timestamptz; evidence_created timestamptz;
                current_policy_updated_at timestamptz;
        BEGIN
            SELECT legal_hold, retention_until, created_at, retention_policy_updated_at
              INTO current_hold, current_retention, evidence_created, current_policy_updated_at
              FROM hub_evidence WHERE id = NEW.evidence_id FOR UPDATE;
            IF evidence_created IS NULL THEN
                RAISE EXCEPTION USING ERRCODE = '23503',
                    MESSAGE = 'retention event evidence does not exist';
            END IF;
            IF NEW.occurred_at < evidence_created OR NEW.occurred_at > clock_timestamp() THEN
                RAISE EXCEPTION USING ERRCODE = '23514',
                    MESSAGE = 'event timestamp must follow evidence creation and not be future-dated';
            END IF;
            IF NEW.occurred_at <= current_policy_updated_at THEN
                RAISE EXCEPTION USING ERRCODE = '23514',
                    MESSAGE = 'retention event timestamps must strictly increase';
            END IF;
            IF NEW.previous_legal_hold IS DISTINCT FROM current_hold
               OR NEW.previous_retention_until IS DISTINCT FROM current_retention THEN
                RAISE EXCEPTION USING ERRCODE = '23514',
                    MESSAGE = 'retention event previous state is stale';
            END IF;
            IF NEW.resulting_legal_hold IS NOT DISTINCT FROM current_hold
               AND NEW.resulting_retention_until IS NOT DISTINCT FROM current_retention THEN
                RAISE EXCEPTION USING ERRCODE = '23514',
                    MESSAGE = 'retention event must change policy';
            END IF;
            IF NEW.resulting_retention_until <= evidence_created THEN
                RAISE EXCEPTION USING ERRCODE = '23514',
                    MESSAGE = 'resulting retention must be after evidence creation';
            END IF;
            UPDATE hub_evidence
               SET legal_hold = NEW.resulting_legal_hold,
                   retention_until = NEW.resulting_retention_until,
                   retention_policy_updated_at = NEW.occurred_at
             WHERE id = NEW.evidence_id;
            RETURN NEW;
        END; $$ LANGUAGE plpgsql
        """
    )
    op.execute(
        """CREATE TRIGGER tr_hub_evidence_retention_events_apply
        BEFORE INSERT ON hub_evidence_retention_events
        FOR EACH ROW EXECUTE FUNCTION validate_hub_evidence_retention_event()"""
    )
    op.execute(
        """
        CREATE FUNCTION reject_hub_quality_audit_delete() RETURNS trigger AS $$
        BEGIN
            RAISE EXCEPTION USING ERRCODE = '23503',
                MESSAGE = 'hub quality audit records cannot be deleted';
        END; $$ LANGUAGE plpgsql
    """
    )
    op.execute(
        """
        CREATE FUNCTION validate_hub_discrepancy_insert() RETURNS trigger AS $$
        DECLARE receipt_completed timestamptz;
        BEGIN
            PERFORM 1 FROM hub_receipt_items
            WHERE id = NEW.receipt_item_id AND receipt_session_id = NEW.receipt_session_id
            FOR UPDATE;
            SELECT completed_at INTO receipt_completed FROM hub_receipt_sessions
            WHERE id = NEW.receipt_session_id FOR UPDATE;
            IF receipt_completed IS NOT NULL THEN
                RAISE EXCEPTION USING ERRCODE = '23514',
                    MESSAGE = 'completed receipt sessions are immutable';
            END IF;
            RETURN NEW;
        END; $$ LANGUAGE plpgsql
    """
    )
    op.execute(
        """CREATE TRIGGER tr_hub_discrepancies_receipt_open
        BEFORE INSERT ON hub_discrepancies
        FOR EACH ROW EXECUTE FUNCTION validate_hub_discrepancy_insert()"""
    )
    op.execute(
        """
        CREATE FUNCTION reject_hub_quality_audit_update() RETURNS trigger AS $$
        BEGIN
            RAISE EXCEPTION USING ERRCODE = '23514',
                MESSAGE = 'hub quality audit records are immutable';
        END; $$ LANGUAGE plpgsql
    """
    )
    op.execute(
        "CREATE TRIGGER tr_hub_discrepancies_update_restricted "
        "BEFORE UPDATE ON hub_discrepancies "
        "FOR EACH ROW EXECUTE FUNCTION reject_hub_quality_audit_update()"
    )
    op.execute(
        "CREATE TRIGGER tr_hub_evidence_retention_events_update_restricted "
        "BEFORE UPDATE ON hub_evidence_retention_events "
        "FOR EACH ROW EXECUTE FUNCTION reject_hub_quality_audit_update()"
    )
    for table in (
        "hub_receipt_sessions",
        "hub_receipt_items",
        "hub_discrepancies",
        "hub_qc_sessions",
        "hub_qc_inspections",
        "hub_evidence",
        "hub_evidence_retention_events",
        "hub_remediations",
    ):
        op.execute(
            f"CREATE TRIGGER tr_{table}_delete_restricted BEFORE DELETE ON {table} "
            "FOR EACH ROW EXECUTE FUNCTION reject_hub_quality_audit_delete()"
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "DROP TRIGGER IF EXISTS tr_hub_discrepancies_receipt_open "
        "ON hub_discrepancies"
    )
    op.execute(
        "DROP TRIGGER IF EXISTS tr_hub_discrepancies_update_restricted "
        "ON hub_discrepancies"
    )
    op.execute(
        "DROP TRIGGER IF EXISTS tr_hub_evidence_update_restricted ON hub_evidence"
    )
    op.execute(
        "DROP TRIGGER IF EXISTS tr_hub_evidence_retention_events_apply "
        "ON hub_evidence_retention_events"
    )
    op.execute(
        "DROP TRIGGER IF EXISTS tr_hub_evidence_retention_events_update_restricted "
        "ON hub_evidence_retention_events"
    )
    for table in (
        "hub_receipt_sessions",
        "hub_receipt_items",
        "hub_discrepancies",
        "hub_qc_sessions",
        "hub_qc_inspections",
        "hub_evidence",
        "hub_evidence_retention_events",
        "hub_remediations",
    ):
        op.execute(f"DROP TRIGGER IF EXISTS tr_{table}_delete_restricted ON {table}")
    op.execute(
        "DROP TRIGGER IF EXISTS tr_hub_qc_sessions_reinspection_lineage ON hub_qc_sessions"
    )
    op.execute(
        "DROP TRIGGER IF EXISTS tr_hub_remediations_invariants ON hub_remediations"
    )
    op.execute(
        "DROP TRIGGER IF EXISTS tr_hub_qc_sessions_completed_immutable ON hub_qc_sessions"
    )
    op.execute(
        "DROP TRIGGER IF EXISTS tr_hub_qc_inspections_completed_immutable ON hub_qc_inspections"
    )
    op.execute(
        "DROP TRIGGER IF EXISTS tr_hub_qc_inspections_quantity_safe ON hub_qc_inspections"
    )
    op.execute(
        "DROP TRIGGER IF EXISTS tr_hub_receipt_sessions_completed_immutable ON hub_receipt_sessions"
    )
    op.execute(
        "DROP TRIGGER IF EXISTS tr_hub_receipt_items_quantity_safe ON hub_receipt_items"
    )
    op.execute(
        "ALTER TABLE hub_evidence DROP CONSTRAINT IF EXISTS fk_hub_evidence_remediation_identity"
    )
    op.drop_constraint(
        "fk_hub_qc_sessions_remediation_identity",
        "hub_qc_sessions",
        type_="foreignkey",
    )
    op.drop_table("hub_remediations")
    op.drop_table("hub_evidence_retention_events")
    op.drop_table("hub_evidence")
    op.drop_table("hub_qc_inspections")
    op.drop_table("hub_discrepancies")
    op.drop_table("hub_receipt_items")
    op.drop_table("hub_qc_sessions")
    op.drop_table("hub_receipt_sessions")
    op.drop_constraint(
        "uq_inbound_transfer_items_identity",
        "inbound_transfer_item_allocations",
        type_="unique",
    )
    op.drop_constraint(
        "uq_inbound_transfers_hub_identity", "inbound_transfers", type_="unique"
    )
    op.execute("DROP FUNCTION IF EXISTS reject_hub_quality_audit_delete()")
    op.execute("DROP FUNCTION IF EXISTS reject_hub_quality_audit_update()")
    op.execute("DROP FUNCTION IF EXISTS validate_hub_discrepancy_insert()")
    op.execute("DROP FUNCTION IF EXISTS validate_hub_evidence_retention_event()")
    op.execute("DROP FUNCTION IF EXISTS validate_hub_evidence_update()")
    op.execute("DROP FUNCTION IF EXISTS reject_completed_hub_receipt_update()")
    op.execute("DROP FUNCTION IF EXISTS reject_completed_hub_qc_update()")
    op.execute("DROP FUNCTION IF EXISTS validate_hub_qc_reinspection_lineage()")
    op.execute("DROP FUNCTION IF EXISTS validate_hub_remediation_invariants()")
    op.execute("DROP FUNCTION IF EXISTS validate_hub_qc_inspection_quantity()")
    op.execute("DROP FUNCTION IF EXISTS validate_hub_receipt_item_quantity()")
    op.execute("DROP TYPE IF EXISTS hub_remediation_state")
    op.execute("DROP TYPE IF EXISTS hub_remediation_action")
    op.execute("DROP TYPE IF EXISTS hub_evidence_purpose")
    op.execute("DROP TYPE IF EXISTS hub_qc_decision")
    op.execute("DROP TYPE IF EXISTS hub_quarantine_disposition")
    op.execute("DROP TYPE IF EXISTS hub_discrepancy_type")
    # ### end Alembic commands ###
