"""add_product_made_to_order_and_care_fields

Revision ID: b4a1bb4d0649
Revises: 1ccbab26fbcd
Create Date: 2025-12-18 13:41:24.167060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b4a1bb4d0649'
down_revision: Union[str, None] = '1ccbab26fbcd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Only add new product fields, ignore unrelated changes
    op.add_column('products', sa.Column('made_to_order', sa.Boolean(), server_default=sa.false(), nullable=False))
    op.add_column('products', sa.Column('made_to_order_timeline', sa.String(length=255), nullable=True))
    op.add_column('products', sa.Column('care_instructions', sa.Text(), nullable=True))
    op.add_column('products', sa.Column('fabric_composition', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'fabric_composition')
    op.drop_column('products', 'care_instructions')
    op.drop_column('products', 'made_to_order_timeline')
    op.drop_column('products', 'made_to_order')
    # ### end Alembic commands ###
