"""add_product_type_enum

Revision ID: cd3def809521
Revises: b4a1bb4d0649
Create Date: 2025-12-18 14:01:16.901442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cd3def809521'
down_revision: Union[str, None] = 'b4a1bb4d0649'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create ENUM type first
    producttype_enum = postgresql.ENUM('SINGLE', 'VARIABLE', name='producttype')
    producttype_enum.create(op.get_bind(), checkfirst=True)

    # Add product_type column with enum
    op.add_column('products', sa.Column('product_type', producttype_enum, server_default='SINGLE', nullable=False))
    op.create_index(op.f('ix_products_product_type'), 'products', ['product_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_product_type'), table_name='products')
    op.drop_column('products', 'product_type')

    # Drop ENUM type
    producttype_enum = postgresql.ENUM('SINGLE', 'VARIABLE', name='producttype')
    producttype_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
